### PR TITLE
Update to support VS 2017

### PR DESCRIPTION
**Pull request by jwestes**

### CODE REVIEW

**Comment by codingphil** [comment]
It seems that the original project is not maintained any more so IMHO it is unlikely that it will be merged.
Even though I like your pull request - built the extension myself, installed the visx and BuildVision is working in VS2017.

Many thanks!

**Comment by roalz** [comment]
Crap! Is anyone volunteering to takeover this project?

**Comment by YousufAzadSami** [comment]
I hope someone carries the torch

On Mar 10, 2017 4:51 PM, "Roal Zanazzi" <notifications@github.com> wrote:

Crap! Is anyone volunteering to takeover this project?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nagits/BuildVision/pull/20#issuecomment-285638906>, or mute
the thread

**Comment by Atrejoe** [comment]
I do not volunteer to take over, but I háve included a release in my fork of @jwestes' fork:

https://github.com/Atrejoe/BuildVision/releases/tag/v1.3.1.30

I had some warnings during installation, but all works well.

**Comment by nagits** [comment]
PR #23 merged.

**Pull request closed without merging**
